apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster1
  region: us-east-1

addons:
- name: aws-ebs-csi-driver
  version: v1.23.0-eksbuild.1
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
  
managedNodeGroups:
  - name: dev-cluster
    instanceType: t3.medium
    minSize: 2
    maxSize: 5
    privateNetworking: true
    volumeSize: 50
    tags:
      Name: dev-cluster
