apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sre-stack
  region: us-west-2
  version: "1.27"

addons:
- name: aws-ebs-csi-driver
  version: v1.23.0-eksbuild.1
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
  
managedNodeGroups:
  - name: app-ng
    instanceType: c6a.large
    minSize: 3
    maxSize: 6
    privateNetworking: true
    labels:
      workload: app
    volumeSize: 50
    spot: true
    tags:
      Name: app
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true

  - name: persistent-ng
    instanceType: t3.xlarge
    minSize: 2
    maxSize: 2
    privateNetworking: true
    labels:
      workload: persistent
    volumeSize: 50
    spot: true
    tags:
      Name: sre-stack
    taints:
      - key: persistent
        value: "true"
        effect: NoSchedule
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true

  - name: observability-ng
    instanceType: t3.xlarge
    minSize: 2
    maxSize: 3
    privateNetworking: true
    labels:
      workload: o11y
    volumeSize: 50
    spot: true
    tags:
      Name: prod-cluster
    taints:
      - key: o11y
        value: "true"
        effect: NoSchedule
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true

  - name: loadgen-ng
    instanceType: c5.xlarge
    minSize: 1
    maxSize: 1
    privateNetworking: true
    labels:
      workload: loadgen
    volumeSize: 20
    spot: true
    tags:
      Name: loadgen
    taints:
      - key: loadgen
        value: "true"
        effect: NoSchedule
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true