apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: dev-cluster
    instanceType: t3.medium
    minSize: 3
    maxSize: 5
    privateNetworking: true
    volumeSize: 50
    tags:
      Name: dev-cluster
