apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: monitoring 
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-psql
  namespace: monitoring 
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16.1-bullseye
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres" # Username
            - name: POSTGRES_PASSWORD
              value: "postgres" # Password
      tolerations:
        - key: "o11y"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        workload: "o11y"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 1Gi
