apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: sock-shop
spec:
  hosts:
  - "*"
  gateways:
  - sock-shop-gateway
  http:
  - match:
    - uri:
        exact: /grafana
    - uri:
        prefix: /grafana/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: prometheus-stack-grafana.monitoring.svc.cluster.local
        port:
          number: 80
