apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: details-scaledobject
  namespace: bookinfo-prod
spec:
  scaleTargetRef:
    kind: Deployment                                       # Optional. Default: Deployment
    name: details-v1                               # Mandatory. Must be in the same namespace as the ScaledObject
  pollingInterval:  30                                     # Optional. Default: 30 seconds
  cooldownPeriod:   300                                    # Optional. Default: 300 seconds
  minReplicaCount: 1                                       # Optional. Default: 0
  maxReplicaCount: 5                                       # Optional. Default: 100
  advanced:                                                # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
      query: |
        60 * sum(rate(istio_requests_total{destination_workload=~"details-v1",destination_workload_namespace="bookinfo-prod",reporter="destination",response_code="200", source_workload!="istio-ingressgateway"}[1m])) by (destination_workload)
      threshold: '100'
