apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cart
spec:
  hosts:
  - cart
  http:
  - route:
    - destination:
        host: cart
        port:
          number: 8080
