apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  labels:
    service: dispatch
spec:
  replicas: {{ .Values.catalogue.replicas }}
  selector:
    matchLabels:
      service: dispatch
  template:
    metadata:
      labels:
        service: dispatch
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: dispatch
        image: {{ .Values.image.repo }}/rs-dispatch:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- if .Values.instana.enabled }}
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        {{- end }}
          - name: AMQP_HOST
            value: {{ .Values.amqp_host }}
        resources:
          {{- toYaml .Values.catalogue.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.dispatch.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dispatch.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dispatch.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
