apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-seeder
  labels:
    service: mongodb-seeder
spec:
  template:
    spec:
      containers:
      - name: mongodb-seeder
        image: hashfyre/robotshop-mongodb-seeder
        args:
          - /bin/bash
          - -c
          - /wait && /opt/seeds/seeder.sh
        env:
          - name: MONGO_URL
            value: {{ .Values.mongo_url }}
          - name: TIMEOUT
            value: "600"
          - name: WAIT_HOSTS
            value: {{ .Values.mongo_url }}:3306
          - name: WAIT_HOSTS_TIMEOUT
            value: "300"
          - name: WAIT_HOST_CONNECT_TIMEOUT
            value: "30"
          - name: WAIT_SLEEP_INTERVAL
            value: "30"
        resources:
          {{- toYaml .Values.mongodbseeder.resources | nindent 12 }}
      restartPolicy: OnFailure
      {{- with .Values.users.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.users.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.users.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 4      