{{ if eq .Values.stack_mode "local" }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
data:
  rootPassword: {{ .Values.mysql_root_password | b64enc | quote }}
  userPassword: c2VjcmV0
{{- end }}