apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shipping
spec:
  hosts:
  - shipping
  http:
  - route:
    - destination:
        host: shipping
        port:
          number: 8080
