apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    service: user
spec:
  replicas: {{ .Values.user.replicas }}
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      labels:
        service: user
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: user
        image: {{ .Values.image.repo }}/rs-user:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          # agent networking access
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: MONGO_URL
            value: {{ .Values.mongo_url }}/user
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.user.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.user.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.user.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.user.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
